---

- name: Create Initial Configuration
  hosts: "{{ api_origin }}"
  gather_facts: False
  vars_files:
    - answerfile.yml
  environment:
    http_proxy: ''
    https_proxy: ''
  tasks:
    - name: Create Transport Zone
      run_once: true
      uri:
        url: https://{{ nodes.nsxMan.ipAddress }}/api/v1/transport-zones
        method: POST
        user: admin
        password: "{{ nsxAdminPass }}"
        HEADER_Content-Type: "application/json"
        body: "{ \"display_name\": \"{{ transportZoneName }}\", \"host_switch_name\":\"{{ hostSwitchName }}\", \"description\": \" Created by Ansible\", \"transport_type\":\"{{ tzType }}\" }"
        force_basic_auth: yes
        validate_certs: no
        status_code: 201
        body_format: json
        use_proxy: no
      register: tzone

    - name: Create IP Pool
      run_once: true
      uri:
        url: https://{{ nodes.nsxMan.ipAddress }}/api/v1/pools/ip-pools
        method: POST
        user: admin
        password: "{{ nsxAdminPass }}"
        HEADER_Content-Type: "application/json"
        body: "{ \"display_name\": \"{{ ippool.name }}\", \"description\": \" Created by Ansible\", \"subnets\": [ { \"allocation_ranges\": [ { \"start\": \"{{ ippool.start }}\", \"end\": \"{{ ippool.end }}\" }   ],\"gateway_ip\": \"{{ ippool.gw }}\", \"cidr\": \"{{ ippool.cidr }}\"  }  ]  }"
        force_basic_auth: yes
        validate_certs: no
        status_code: 201
        body_format: json
        use_proxy: no
      register: ippool

    - name: Create Uplink Hostswitch Profile for Overlay
      run_once: true
      uri:
        url: https://{{ nodes.nsxMan.ipAddress }}/api/v1/host-switch-profiles
        method: POST
        user: admin
        password: "{{ nsxAdminPass }}"
        HEADER_Content-Type: "application/json"
        body: "{ \"resource_type\" : \"UplinkHostSwitchProfile\", \"description\" : \"Created by Ansible to assign this hostswitch profile to the Edge for overlay\", \"display_name\" : \"nsx-edge-uplink-hostswitch-profile\", \"transport_vlan\" : \"{{ transport_vlan }}\", \"teaming\" : { \"active_list\" : [ { \"uplink_type\" : \"PNIC\", \"uplink_name\" : \"uplink-1\" } ], \"standby_list\" : [ ], \"policy\" : \"FAILOVER_ORDER\" }, \"mtu\" : 1600 } "
        force_basic_auth: yes
        validate_certs: no
        status_code: 201
        body_format: json
        use_proxy: no
      register: hsprofile

    - name: Get Edge node UUID
      uri:
        url: https://{{ nodes.nsxMan.ipAddress }}/api/v1/fabric/nodes
        method: GET
        user: admin
        password: "{{ nsxAdminPass }}"
        HEADER_Content-Type: "application/json"
        force_basic_auth: yes
        validate_certs: no
        status_code: 200
        body_format: json
        use_proxy: no
      register: edgeuuid

    - name: Create Transport Node from Edge
      run_once: true
      uri:
        url: https://{{ nodes.nsxMan.ipAddress }}/api/v1/transport-nodes
        method: POST
        user: admin
        password: "{{ nsxAdminPass }}"
        HEADER_Content-Type: "application/json"
        body: "{ \"description\" : \"Edge Transport Node created by Ansible\", \"display_name\" : \"{{ nodes.nsxEdge.hostname }}\", \"node_id\" : \"{{ edgeuuid.json.results[0].id }}\", \"transport_zone_endpoints\" : [ { \"transport_zone_id\" : \"{{ tzone.json.id }}\" } ], \"host_switches\" : [ { \"host_switch_profile_ids\" : [ { \"value\" : \"{{ hsprofile.json.id }}\", \"key\" : \"UplinkHostSwitchProfile\" } ], \"host_switch_name\" : \"{{ hostSwitchName }}\", \"pnics\" : [ { \"device_name\" : \"fp-eth1\", \"uplink_name\" : \"uplink-1\" } ], \"static_ip_pool_id\" : \"{{ ippool.json.id }}\" } ] } "
        force_basic_auth: yes
        validate_certs: no
        status_code: 201
        body_format: json
        use_proxy: no
      register: tnode

    - name: Create Edge Cluster
      run_once: true
      uri:
        url: https://{{ nodes.nsxMan.ipAddress }}/api/v1/edge-clusters
        method: POST
        user: admin
        password: "{{ nsxAdminPass }}"
        HEADER_Content-Type: "application/json"
        body: "{ \"cluster_profile_bindings\": [], \"members\": [ { \"transport_node_id\":\"{{ tnode.json.id}}\" } ], \"display_name\": \"EdgeCluster1\", \"description\":\"Created by Ansible\" }"
        force_basic_auth: yes
        validate_certs: no
        status_code: 201
        body_format: json
        use_proxy: no
      register: edgecluster

    - name: Get Edge Cluster ID
      uri:
        url: https://{{ nodes.nsxMan.ipAddress }}/api/v1/edge-clusters
        method: GET
        user: admin
        password: "{{ nsxAdminPass }}"
        HEADER_Content-Type: "application/json"
        force_basic_auth: yes
        validate_certs: no
        status_code: 200
        body_format: json
        use_proxy: no
      register: edgecl

    - name: Create T0 Router
      run_once: true
      uri:
        url: https://{{ nodes.nsxMan.ipAddress }}/api/v1/logical-routers
        method: POST
        user: admin
        password: "{{ nsxAdminPass }}"
        HEADER_Content-Type: "application/json"
        body: "{ \"description\": \"Default T0 Router created by Ansible!!!\", \"display_name\": \"{{ t0.name }}\", \"edge_cluster_id\": \"{{ edgecl.json.results[0].id }}\", \"router_type\": \"TIER0\", \"high_availability_mode\": \"{{ t0.ha }}\" }"
        force_basic_auth: yes
        validate_certs: no
        status_code: 201
        body_format: json
        use_proxy: no
      register: t0
  tags: initialconf

